name: CI/CD Pipeline - AI Trading Bot

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  release:
    types: [published]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest python-dotenv pyinstaller

      # Create .env dynamically with GitHub Secrets
      - name: Create .env file
        run: |
          echo "BINANCE_API_KEY=${{ secrets.BINANCE_API_KEY }}" >> .env
          echo "BINANCE_API_SECRET=${{ secrets.BINANCE_API_SECRET }}" >> .env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          echo "CRYPTOPANIC_API_KEY=${{ secrets.CRYPTOPANIC_API_KEY }}" >> .env

      # Run tests
      - name: Run tests
        run: |
          PYTHONPATH=. pytest tests/ --maxfail=1 --disable-warnings -q

  build-exe:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.event_name == 'release'

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      # Build executable using build.spec
      - name: Build executable
        run: |
          pyinstaller build.spec
          ls dist/AI_Trading_Bot

      # Upload artifact to the release
      - name: Upload executable
        uses: softprops/action-gh-release@v1
        with:
          files: dist/AI_Trading_Bot/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
